/**
 * Hán-Việt readings for characters Unihan's kVietnamese field omits.
 *
 * Unihan only carries kVietnamese for ~8,300 characters, and crucially it
 * attaches them to *traditional* forms. The build script already falls back
 * through kTraditionalVariant, but that still leaves 348 characters in HSK 1-6
 * with no reading at all — and they are not obscure ones. 儿, 面, 电, 爱, 这,
 * 问 and 就 are among the most frequent characters in the language; without
 * them roughly one in six HSK 1-4 words would have no Hán-Việt bridge.
 *
 * These are the standard Sino-Vietnamese readings from Thiều Chửu / Hán-Việt
 * Từ điển conventions. Where a character has several readings, the one listed
 * is the one used in the modern compounds that actually appear in HSK.
 */
export const HANVIET_SUPPLEMENT: Record<string, string> = {
  儿: "nhi",
  面: "diện",
  电: "điện",
  以: "dĩ",
  量: "lượng",
  爱: "ái",
  问: "vấn",
  办: "biện",
  题: "đề",
  饭: "phạn",
  假: "giả",
  餐: "xan",
  游: "du",
  这: "giá",
  者: "giả",
  赛: "trại",
  资: "tư",
  北: "bắc",
  告: "cáo",
  就: "tựu",
  改: "cải",
  酒: "tửu",
  型: "hình",
  笑: "tiếu",
  米: "mễ",
  而: "nhi",
  食: "thực",
  直: "trực",
  录: "lục",
  优: "ưu",
  赶: "cản",
  值: "trị",
  线: "tuyến",
  识: "thức",
  雨: "vũ",
  做: "tố",
  怕: "phạ",
  仅: "cận",
  父: "phụ",
  乡: "hương",
  汇: "hối",
  码: "mã",
  维: "duy",
  签: "thiêm",
  跑: "bào",
  睡: "thụy",
  静: "tĩnh",
  刚: "cương",
  换: "hoán",
  套: "sáo",
  误: "ngộ",
  邮: "bưu",
  范: "phạm",
  环: "hoàn",
  构: "cấu",
  幕: "mạc",
  菜: "thái",
  鸡: "kê",
  汽: "khí",
  坐: "tọa",
  够: "cấu",
  春: "xuân",
  际: "tế",
  街: "nhai",
  卡: "ca",
  靠: "kháo",
  脸: "kiểm",
  亮: "lượng",
  疼: "đông",
  握: "ác",
  材: "tài",
  浪: "lãng",
  暖: "noãn",
  烟: "yên",
  操: "thao",
  赞: "tán",
  购: "cấu",
  率: "suất",
  伙: "hỏa",
  梦: "mộng",
  秘: "bí",
  辑: "tập",
  厅: "sảnh",
  击: "kích",
  偷: "thâu",
  炸: "tạc",
  档: "đáng",
  恰: "kháp",
  爸: "ba",
  帮: "bang",
  净: "tịnh",
  蛋: "đản",
  肉: "nhục",
  岁: "tuế",
  爷: "gia",
  桌: "trác",
  遍: "biến",
  但: "đãn",
  脚: "cước",
  碰: "bính",
  挺: "đĩnh",
  雪: "tuyết",
  概: "khái",
  婚: "hôn",
  营: "doanh",
  旧: "cựu",
  怪: "quái",
  何: "hà",
  幸: "hạnh",
  需: "nhu",
  售: "thụ",
  席: "tịch",
  临: "lâm",
  疑: "nghi",
  酸: "toan",
  弯: "loan",
  聊: "liêu",
  摩: "ma",
  询: "tuân",
  鼓: "cổ",
  掌: "chưởng",
  键: "kiện",
  频: "tần",
  启: "khải",
  挨: "ai",
  爆: "bạo",
  藏: "tàng",
  峰: "phong",
  阔: "khoát",
  融: "dung",
  祖: "tổ",
  很: "ngận",
  她: "tha",
  页: "hiệt",
  辆: "lượng",
  懂: "đổng",
  该: "cai",
  它: "tha",
  闻: "văn",
  夏: "hạ",
  椅: "y",
  咱: "trớ",
  嘴: "chủy",
  较: "giảo",
  衬: "sấn",
  甜: "điềm",
  赢: "doanh",
  泳: "vịnh",
  矮: "ải",
  薄: "bạc",
  梯: "thê",
  堵: "đổ",
  翻: "phiên",
  厚: "hậu",
  既: "ký",
  闪: "thiểm",
  塑: "tố",
  缩: "súc",
  贴: "thiếp",
  亚: "á",
  扮: "bán",
  耐: "nại",
  偿: "thường",
  猜: "sai",
  叉: "xoa",
  肠: "trường",
  尝: "thường",
  汗: "hãn",
  脆: "thúy",
  糕: "cao",
  震: "chấn",
  锅: "oa",
  革: "cách",
  沟: "câu",
  估: "cổ",
  胡: "hồ",
  泼: "bát",
  驶: "sử",
  竞: "cạnh",
  鸭: "áp",
  貌: "mạo",
  铃: "linh",
  陪: "bồi",
  赔: "bồi",
  骗: "biển",
  葡: "bồ",
  萄: "đào",
  抢: "thưởng",
  悄: "tiễu",
  稍: "sảo",
  伸: "thân",
  剩: "thặng",
  鼠: "thử",
  摔: "suất",
  抬: "đài",
  卧: "ngọa",
  糟: "tao",
  歉: "khiểm",
  异: "dị",
  诞: "đản",
  党: "đảng",
  抵: "để",
  裂: "liệt",
  衡: "hành",
  盟: "minh",
  鉴: "giám",
  纠: "củ",
  赖: "lại",
  薯: "thự",
  径: "kính",
  娃: "oa",
  娱: "ngu",
  账: "trướng",
  赚: "trám",
  饿: "ngạ",
  您: "nâm",
  谁: "thùy",
  昨: "tạc",
  饱: "bão",
  喊: "hảm",
  饺: "giáo",
  筷: "khoái",
  努: "nỗ",
  篇: "thiên",
  碗: "uyển",
  澡: "táo",
  睛: "tình",
  济: "tế",
  咖: "ca",
  啡: "phi",
  啤: "bia",
  阿: "a",
  裹: "khỏa",
  笨: "bổn",
  辩: "biện",
  戴: "đái",
  肚: "đỗ",
  锻: "đoán",
  逛: "cuống",
  归: "quy",
  缓: "hoãn",
  巨: "cự",
  圾: "ngập",
  俩: "lưỡng",
  晒: "sái",
  申: "thân",
  暑: "thử",
  袜: "miệt",
  谓: "vị",
  咸: "hàm",
  迅: "tấn",
  盐: "diêm",
  综: "tống",
  鼻: "tỵ",
  玻: "pha",
  贷: "thải",
  挡: "đáng",
  躲: "đóa",
  弃: "khí",
  析: "tích",
  辅: "phụ",
  籍: "tịch",
  恢: "khôi",
  肌: "cơ",
  挤: "tễ",
  肩: "kiên",
  郊: "giao",
  届: "giới",
  颗: "khỏa",
  贸: "mậu",
  秒: "miểu",
  龄: "linh",
  肤: "phu",
  瞧: "tiều",
  傻: "sọa",
  蔬: "sơ",
  胃: "vị",
  肃: "túc",
  邀: "yêu",
  幽: "u",
  尤: "vưu",
  犹: "do",
  豫: "dự",
  谊: "nghị",
  饰: "sức",
  醉: "túy",
  奔: "bôn",
  拨: "bát",
  踩: "thải",
  仓: "thương",
  昌: "xương",
  储: "trữ",
  醋: "thố",
  吊: "điếu",
  蹲: "tồn",
  殖: "thực",
  肺: "phế",
  岗: "cương",
  稿: "cảo",
  刮: "quát",
  湾: "loan",
  狠: "ngoan",
  宏: "hoành",
  壶: "hồ",
  祥: "tường",
  嘉: "gia",
  捡: "kiểm",
  焦: "tiêu",
  悟: "ngộ",
  舰: "hạm",
  跨: "khóa",
  啦: "lạp",
  懒: "lãn",
  嘛: "ma",
  馒: "man",
  棉: "miên",
  膜: "mô",
  墨: "mặc",
  扭: "nữu",
  盼: "phán",
  氛: "phân",
  牵: "khiên",
  绪: "tự",
  券: "khoán",
  践: "tiễn",
  寺: "tự",
  塔: "tháp",
  趟: "thảng",
  踢: "thích",
  讯: "tấn",
  吞: "thôn",
  挖: "oạt",
  牺: "hy",
  菌: "khuẩn",
  锋: "phong",
  薪: "tân",
  悬: "huyền",
  循: "tuần",
  氧: "dưỡng",
  愉: "du",
  允: "duẫn",
  耀: "diệu",
  慧: "tuệ",
  粥: "chúc",
  煮: "chử",
  宅: "trạch",
  咨: "tư",
  钻: "toản",

  // ---------------------------------------------------------------------
  // Disambiguation, not gap-filling.
  //
  // Unihan's kVietnamese sometimes lists several readings, and they are NOT
  // ordered with the Sino-Vietnamese one first — the field interleaves
  // Hán-Việt readings with Nôm (vernacular) ones. 每 is listed as
  // "hỏi mỏi mọi mỗi mủ mủi mũi" (Hán-Việt "mỗi" is fourth) and 百 as
  // "bá bách trăm" ("trăm" being the native numeral, not a reading at all).
  // Taking the first token yields nonsense, so every multi-reading character
  // in HSK 1-6 is pinned here to its standard Hán-Việt reading.
  东: "đông",
  冲: "xung",
  托: "thác",
  担: "đảm",
  拐: "quải",
  捐: "quyên",
  更: "canh",
  栏: "lan",
  校: "hiệu",
  案: "án",
  榜: "bảng",
  死: "tử",
  残: "tàn",
  每: "mỗi",
  沙: "sa",
  没: "một",
  泥: "nê",
  洪: "hồng",
  添: "thiêm",
  湿: "thấp",
  激: "kích",
  炉: "lô",
  璃: "ly",
  番: "phiên",
  百: "bách",
  盆: "bồn",
  看: "khán",
  眼: "nhãn",
  研: "nghiên",
  示: "thị",
  租: "tô",
  第: "đệ",
  年: "niên",
};

/**
 * Word-level Hán-Việt readings that differ from naive per-character composition.
 *
 * Usually composing character readings works, but some characters have several
 * readings and the compound picks a different one than the per-character
 * default (中国 is "Trung Quốc", not "Trung Cốc"; 银行 is "ngân hàng", not
 * "ngân hành"). These override the composed form.
 */
export const WORD_HANVIET_OVERRIDES: Record<string, string> = {
  中国: "Trung Quốc",
  银行: "ngân hàng",
  行李: "hành lý",
  自行车: "tự hành xa",
  可乐: "khả lạc",
  音乐: "âm nhạc",
  快乐: "khoái lạc",
  乐器: "nhạc khí",
  的话: "đích thoại",
  地方: "địa phương",
  方便: "phương tiện",
  便宜: "tiện nghi",
  重要: "trọng yếu",
  重新: "trùng tân",
  长大: "trưởng đại",
  校长: "hiệu trưởng",
  成长: "thành trưởng",
  会计: "kế toán",
  教学: "giáo học",
  睡觉: "thụy giác",
  感觉: "cảm giác",
  觉得: "giác đắc",
  为了: "vị liễu",
  因为: "nhân vi",
  认为: "nhận vi",
  以为: "dĩ vi",
  作为: "tác vi",
  行为: "hành vi",
  差不多: "sai bất đa",
  出差: "xuất sai",
  相同: "tương đồng",
  照相: "chiếu tướng",
  相信: "tương tín",
  干净: "can tịnh",
  干部: "cán bộ",
  好处: "hảo xứ",
  爱好: "ái hảo",
  还是: "hoàn thị",
  还有: "hoàn hữu",
  归还: "quy hoàn",
};
